import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import * as XLSX from "xlsx";
import { afterEach, describe, expect, it, vi } from "vitest";

import {
  buildSnapshotFromWorkbook,
  buildWorkbookSnapshotFromWorkbook,
  extractWorkbookImages,
  resolveSheetName
} from "@/src/lib/tam/importer";

const FIXED_DATE = new Date("2026-03-08T00:00:00.000Z");
const tempDirs: string[] = [];

afterEach(async () => {
  vi.unstubAllGlobals();

  await Promise.all(
    tempDirs.splice(0).map((tempDir) =>
      rm(tempDir, { recursive: true, force: true })
    )
  );
});

describe("buildSnapshotFromWorkbook", () => {
  it("parses headers and rows while preserving all columns", () => {
    const workbook = XLSX.utils.book_new();
    const sheet = XLSX.utils.aoa_to_sheet([
      [" Market ", "Revenue", "Active"],
      ["North", 1200, true],
      ["South", "", false]
    ]);
    XLSX.utils.book_append_sheet(workbook, sheet, "TAM");

    const snapshot = buildSnapshotFromWorkbook({
      workbook,
      sourceFile: "data/raw/tam.xlsx",
      preferredSheet: "TAM",
      generatedAt: FIXED_DATE
    });

    expect(snapshot.columns).toEqual(["Market", "Revenue", "Active"]);
    expect(snapshot.rowCount).toBe(2);
    expect(snapshot.rows).toEqual([
      { Market: "North", Revenue: 1200, Active: true },
      { Market: "South", Revenue: null, Active: false }
    ]);
  });

  it("falls back to first sheet if TAM is missing", () => {
    const workbook = XLSX.utils.book_new();
    const firstSheet = XLSX.utils.aoa_to_sheet([
      ["Region", "Units"],
      ["West", 55]
    ]);
    XLSX.utils.book_append_sheet(workbook, firstSheet, "ExportData");

    const selectedSheet = resolveSheetName(workbook, "TAM");
    const snapshot = buildSnapshotFromWorkbook({
      workbook,
      sourceFile: "data/raw/tam.xlsx",
      preferredSheet: "TAM",
      generatedAt: FIXED_DATE
    });

    expect(selectedSheet).toBe("ExportData");
    expect(snapshot.columns).toEqual(["Region", "Units"]);
    expect(snapshot.rows).toEqual([{ Region: "West", Units: 55 }]);
  });

  it("creates deterministic snapshot output when timestamp is fixed", () => {
    const workbook = XLSX.utils.book_new();
    const sheet = XLSX.utils.aoa_to_sheet([
      ["Category", "Share"],
      ["A", 0.25]
    ]);
    XLSX.utils.book_append_sheet(workbook, sheet, "TAM");

    const first = buildSnapshotFromWorkbook({
      workbook,
      sourceFile: "data/raw/tam.xlsx",
      generatedAt: FIXED_DATE
    });
    const second = buildSnapshotFromWorkbook({
      workbook,
      sourceFile: "data/raw/tam.xlsx",
      generatedAt: FIXED_DATE
    });

    expect(first).toEqual(second);
    expect(first.generatedAt).toBe("2026-03-08T00:00:00.000Z");
  });

  it("imports all workbook sheets for tab rendering", () => {
    const workbook = XLSX.utils.book_new();
    const firstSheet = XLSX.utils.aoa_to_sheet([
      ["Substrate", "Enabled"],
      ["Acrylic", "Yes"]
    ]);
    const secondSheet = XLSX.utils.aoa_to_sheet([
      ["Region", "Demand"],
      ["US", 42]
    ]);

    XLSX.utils.book_append_sheet(workbook, firstSheet, "Substrates");
    XLSX.utils.book_append_sheet(workbook, secondSheet, "Markets");

    const workbookSnapshot = buildWorkbookSnapshotFromWorkbook({
      workbook,
      sourceFile: "data/raw/tam.xlsx",
      generatedAt: FIXED_DATE
    });

    expect(workbookSnapshot.defaultSheet).toBe("Substrates");
    expect(workbookSnapshot.sheets.map((sheet) => sheet.name)).toEqual([
      "Substrates",
      "Markets"
    ]);
    expect(workbookSnapshot.sheets[1].rows[0]).toEqual({ Region: "US", Demand: 42 });
  });

  it("drops blank autogenerated columns for material sheets", () => {
    const workbook = XLSX.utils.book_new();
    const sheet = XLSX.utils.aoa_to_sheet([
      ["Product Category", "", "Machine used For Production"],
      ["Wall Sign", null, "CO2 Engraving"],
      ["Award", "", "UV Printing"]
    ]);
    XLSX.utils.book_append_sheet(workbook, sheet, "Acrylic");

    const snapshot = buildSnapshotFromWorkbook({
      workbook,
      sourceFile: "data/raw/tam.xlsx",
      preferredSheet: "Acrylic",
      generatedAt: FIXED_DATE
    });

    expect(snapshot.columns).toEqual(["Product Category", "Machine used For Production"]);
    expect(snapshot.rows).toEqual([
      {
        "Product Category": "Wall Sign",
        "Machine used For Production": "CO2 Engraving"
      },
      {
        "Product Category": "Award",
        "Machine used For Production": "UV Printing"
      }
    ]);
  });

  it("extracts formula-based images and preserves manual uploads during re-import", async () => {
    const workbook = XLSX.utils.book_new();
    const sheet = XLSX.utils.aoa_to_sheet([
      ["Product", "", "Market"],
      ["Acrylic Sign", null, "Cronk Market"],
      [null, null, null],
      ["Desk Plaque", null, "Cronk Market"]
    ]);
    sheet.B2 = { t: "s", f: 'IMAGE("https://example.com/acrylic.png")', v: "" };
    sheet.B4 = { t: "s", f: 'IMAGE("https://example.com/plaque.jpg?size=large")', v: "" };
    sheet["!ref"] = "A1:C4";
    XLSX.utils.book_append_sheet(workbook, sheet, "Acrylic");

    const tempDir = await mkdtemp(path.join(tmpdir(), "tam-importer-"));
    tempDirs.push(tempDir);
    const manualDir = path.join(tempDir, "manual");
    await mkdir(manualDir, { recursive: true });
    const manualFilePath = path.join(manualDir, "keep.txt");
    await writeFile(manualFilePath, "keep", "utf8");

    const fetchMock = vi.fn(async (url: string) => {
      const contentType = url.includes(".jpg") ? "image/jpeg" : "image/png";
      return new Response(Buffer.from(url), {
        status: 200,
        headers: { "Content-Type": contentType }
      });
    });
    vi.stubGlobal("fetch", fetchMock);

    const imagesBySheet = await extractWorkbookImages({
      workbook,
      outputDir: tempDir,
      publicBasePath: "/tam-assets/test"
    });

    expect(imagesBySheet.Acrylic).toEqual([
      {
        rowIndex: 0,
        colIndex: 1,
        src: "/tam-assets/test/acrylic-r1-c1.png",
        fileName: "acrylic.png"
      },
      {
        rowIndex: 1,
        colIndex: 1,
        src: "/tam-assets/test/acrylic-r3-c1.jpg",
        fileName: "plaque.jpg"
      }
    ]);
    expect(fetchMock).toHaveBeenCalledTimes(2);
    expect(existsSync(manualDir)).toBe(true);
    expect(await readFile(manualFilePath, "utf8")).toBe("keep");
  });
});
