import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

interface CommandResult {
  label: string;
  command: string;
  exitCode: number;
}

interface NpmInvocation {
  command: string;
  leadingArgs: string[];
  displayCommand: string;
}

const HANDOFF_PATH = path.join("docs", "agents", "chat-handoff.md");

async function run(): Promise<void> {
  const rootDir = process.cwd();
  const commandResults = [
    runNpmCommand(rootDir, "agent:refresh", ["run", "agent:refresh"]),
    runNpmCommand(rootDir, "test", ["run", "test"])
  ];

  const branch = runProcess(rootDir, "git", ["rev-parse", "--abbrev-ref", "HEAD"]).stdout.trim() || "unknown";
  const commit = runProcess(rootDir, "git", ["rev-parse", "--short", "HEAD"]).stdout.trim() || "unknown";
  const gitStatusOutput = runProcess(rootDir, "git", ["status", "--short"]).stdout.trim();
  const changedFiles = gitStatusOutput
    ? gitStatusOutput
        .split(/\r?\n/)
        .map((line) => line.trim())
        .filter(Boolean)
    : [];

  const handoffMarkdown = [
    "# Chat Handoff",
    "",
    "> Generated by `npm run handoff`. Re-run this command before switching chats.",
    "",
    "## Status",
    "",
    `- Generated at: \`${new Date().toISOString()}\``,
    `- Branch: \`${branch}\``,
    `- HEAD: \`${commit}\``,
    "",
    "## Validation",
    "",
    ...commandResults.map((result) =>
      `- \`${result.label}\` via \`${result.command}\`: ${result.exitCode === 0 ? "passed" : `failed (exit ${result.exitCode})`}`
    ),
    "",
    "## Changed Files",
    "",
    ...(changedFiles.length > 0
      ? changedFiles.map((line) => `- \`${line}\``)
      : ["- Working tree clean."]),
    "",
    "## Next Chat Start",
    "",
    "1. Read `AGENTS.md`.",
    "2. Read `docs/agents/README.md`.",
    "3. Read `docs/agents/repository-map.md`.",
    "4. Review the changed files above before editing.",
    "5. If validation failed, fix that first.",
    ""
  ].join("\n");

  const outputPath = path.join(rootDir, HANDOFF_PATH);
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, handoffMarkdown, "utf8");

  if (commandResults.some((result) => result.exitCode !== 0)) {
    process.exit(1);
  }
}

function runNpmCommand(rootDir: string, label: string, args: string[]): CommandResult {
  const npmInvocation = resolveNpmInvocation();
  const result = spawnSync(npmInvocation.command, [...npmInvocation.leadingArgs, ...args], {
    cwd: rootDir,
    stdio: "inherit"
  });

  return {
    label,
    command: `${npmInvocation.displayCommand} ${args.join(" ")}`,
    exitCode: result.status ?? 1
  };
}

function resolveNpmInvocation(): NpmInvocation {
  if (process.platform !== "win32") {
    return {
      command: "npm",
      leadingArgs: [],
      displayCommand: "npm"
    };
  }

  const nodeCandidates = [
    "C:\\Program Files\\nodejs\\node.exe",
    "C:\\Program Files (x86)\\nodejs\\node.exe"
  ];
  const npmCliCandidates = [
    "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
    "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
  ];

  const nodePath = nodeCandidates.find((candidate) => existsSync(candidate));
  const npmCliPath = npmCliCandidates.find((candidate) => existsSync(candidate));
  if (nodePath && npmCliPath) {
    return {
      command: nodePath,
      leadingArgs: [npmCliPath],
      displayCommand: `${nodePath} ${npmCliPath}`
    };
  }

  return {
    command: "npm.cmd",
    leadingArgs: [],
    displayCommand: "npm.cmd"
  };
}

function runProcess(rootDir: string, command: string, args: string[]): { stdout: string } {
  const result = spawnSync(command, args, {
    cwd: rootDir,
    encoding: "utf8"
  });

  if (result.status !== 0) {
    return { stdout: "" };
  }

  return {
    stdout: result.stdout ?? ""
  };
}

async function main(): Promise<void> {
  await run();
}

const currentFilePath = fileURLToPath(import.meta.url);
const invokedFilePath = process.argv[1] ? path.resolve(process.argv[1]) : "";

if (currentFilePath === invokedFilePath) {
  main().catch((error) => {
    console.error((error as Error).message);
    process.exit(1);
  });
}
